PS1='\[\033[01;32m\]\u\[\033[00m\] \[\033[01;34m\][\w]\[\033[00m\]\n\$ '

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

export PATH="$PATH:$HOME/.local/bin:$HOME/go/bin:$HOME/.local/lib/npm-packages/bin"
source "$HOME/.cargo/env"

# Calc shortcuts for different types
xcalc() { calc -u "$@ :08x"; }
bcalc() { calc -u "$@ :032b"; }

eval "$(fzf --bash)"
export FZF_DEFAULT_OPTS="--layout=reverse --height=20"

function fzd {
    dest=$(fd -td | fzf --preview="ls -l {}")
    if [ -z "$dest" ]
    then
        echo none selected
    else
        cd $dest
    fi
}
export fzd

function senv {
    # Source python venv
    if [ -z "$1" ]
    then
        v=$(ls $HOME/venvs | fzf)
    else
        v=$1
    fi
    if [ -z "$v" ]
    then
        echo none selected
    else
        source $HOME/venvs/$v/bin/activate
    fi
}
export senv

