PS1='\[\033[01;32m\]\u\[\033[00m\] \[\033[01;34m\][\w]\[\033[00m\]\n\$ '

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

export PATH="$PATH:$HOME/.local/bin:$HOME/go/bin:$HOME/.local/lib/npm-packages/bin"
source "$HOME/.cargo/env"

# Calc shortcuts for different types
xcalc() { calc -u "$@ :08x"; }
bcalc() { calc -u "$@ :032b"; }

eval "$(fzf --bash)"
export FZF_DEFAULT_OPTS="--layout=reverse --height=20"

function fzd {
    dest=$(fd -td | fzf --preview="ls -l {}")
    if [ -z "$dest" ]
    then
        echo none selected
    else
        cd $dest
    fi
}
export fzd

function senv() {
  local cache_file="$HOME/.cache/venv_registry"
  local max_age_seconds=86400  # 1 day

  # Refresh cache if missing or older than 1 day
  if [[ ! -f "$cache_file" ]] || \
     [[ $(( $(date +%s) - $(date +%s -r "$cache_file") )) -gt $max_age_seconds ]]; then
    fd --hidden --no-ignore-vcs \
       --exclude .cache \
       --exclude node_modules \
       --exclude .cargo \
       --exclude .rustup \
       --exclude .local \
       -g 'activate' ~ \
      | rg '(venvs|\.venv)' \
      | sed "s|$HOME/||" \
      | sed 's|/bin/activate||' \
      > "$cache_file"
  fi

  local selected
  selected=$(fzf --prompt="senv> " \
                 --preview="ls $HOME/{}/lib" \
                 < "$cache_file")

  [[ -n "$selected" ]] && source "$HOME/$selected/bin/activate"
}

# Force refresh the cache
function senv_refresh() {
  rm -f "$HOME/.cache/venv_registry"
  senv
}
export senv senv_refresh

eval "$(starship init bash)"
