# Bind C-a as prefix
unbind C-b
set -g prefix C-a

# Global options
set -g escape-time 200
set -g base-index 1
set -g set-titles on
set -g set-titles-string "#I:#W"
set -g default-terminal "screen-256color"

# Bindings
unbind s
unbind M
unbind m

bind c new-window -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"

bind h select-pane -L
bind l select-pane -R
bind j select-pane -D
bind k select-pane -U

bind x kill-pane
bind X kill-window
bind a send-prefix

bind m if '[ #{pane_marked} -eq 1 ]' 'select-pane -M' 'select-pane -m' # Toggle marked pane
bind M join-pane
bind \' { select-window -t '{marked}' ; select-pane -t '{marked}' }

# Copy/Paste
setw -g mode-keys vi

unbind -T copy-mode-vi v
bind -T copy-mode-vi v send-keys -X begin-selection

# Status

set -g status-position top

set -g status-style "bg=terminal,fg=brightyellow"
set -g status-left-style "bg=red,fg=black"
set -g status-right-style "bg=blue,fg=black"
set -g status-justify centre
